### ISSUE TITLE
Migrate from CircleCI to Github Actions

### ISSUE THREAD

**Issue by richscott** [armadaproject/armada#1037] opened 2022-06-01 16:05 UTC
┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-48) by [Unito](https://www.unito.io)

**Comment by jayofdoom** [comment] 2022-06-10 19:42
Unit tests and linting merged, but not required for merging -- we're evaluating it versus Circle CI first.

Integration tests have performance issues that I believe are caused by a smaller runner being used in GHA (this is not configurable; you use their static-sized runners or provide your own). There's a discussion here about how to move forward: https://gr-oss.slack.com/archives/C03F1DS85AQ/p1654807364006189 -- it boils down to three options:
- Investigate hosting our GHA runners
- Revert all test migrations to GHA
- Continue to use a split setup, with unit tests and linting running alongside CodeQL in github actions, with integration tests running in circle ci. This is the option I think gives us the best mix of functionality and quick runtime.

**Comment by jayofdoom** [comment] 2022-08-08 21:12
I have a PoC running tests using paid-for github runners in ~15-17 minutes. https://github.com/jayofdoom/armada/runs/7733643008

There are a handful of things needed before this is ready for landing:
- Do some matrix testing across multiple different instance sizes; be sure we're at the best size
- Ensure in the case where we cannot spawn a runner, we still run integration tests on a free runner (if possible)
- Ensure *all* items supported by circleci (including releases / uploads of docker images) are supported in our GHA

**Comment by stackedsax** [comment] 2022-08-08 23:38
@jayofdoom thanks for doing this.  I've never checked out the paid-for runners -- do we just pay more and maybe get that time down under 10mins?

**Comment by jayofdoom** [comment] 2022-08-08 23:45
I'm not convinced that vertical scaling is possible without actual work to parallelize the tests explicitly. I'm trying to explore those possibilities before doing the cleanup work around this to make it mergeable. (Which will include making sure we're at the point where we have all the performance we can pay for without excess)

For instance, I started something testing before I stepped away this afternoon that is using docker's new build system which might be faster outright, but if it isn't I'm convinced it could be made to be faster with a few changes to our dockerfiles.

**Comment by jayofdoom** [comment] 2022-08-08 23:50
https://github.com/jayofdoom/armada/runs/7736074257 looks like I just gained quite a bit of time just by setting an environment variable 👍

**Comment by jayofdoom** [comment] 2022-08-17 15:22
One #1156 is merged, we'll have the following remaining steps:
- Implement releases in Github Actions
- Disable run of jobs in CircleCI

**Comment by richscott** [comment] 2023-01-24 16:16
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/armadaproject/armada/1037?planning-poker) with Zenhub @ClifHouck @dejanzele @kannon92 @richscott @Sharpz7 @suprjinx

**Comment by Sharpz7** [comment] 2023-08-21 04:12
Migration completed. Wow that was quick!

**Closed by Sharpz7** 2023-08-21 04:12 UTC
